DETECTION_RESULTS_TABLE_NAME = 'detection_results'
ID_DETECTION_RESULT_COLUMN = 'ID_detection_result'
LOCATION_COLUMN = 'location'
DETECTION_TIME_COLUMN = 'detection_time'
AREA_COMPUTED_COLUMN = 'area_computed'
